### ISSUE TITLE
breaking

### ISSUE THREAD

**Issue by haniali1234** [geekwise-alonzo-yrigollen/geekwise-academy#1]
When you minimize the browser it brakes for 2 px then comes back..
if you dont see it let me know

**Comment by geekwise-alonzo-yrigollen** [comment]
okay, thanks i will take care of that. Also, hey when you get a chance,
checkout my cohort tab....it is rendering two images when i only have one?
Can you give me some guidence with that when you get a second?

**Comment by geekwise-alonzo-yrigollen** [comment]
@haniali1234 ready for revue
