### ISSUE TITLE
Navigational Issue

### ISSUE THREAD

**Issue by Sramos9191** [geekwise-alonzo-yrigollen/geekwise-academy#5]
page: global
issue: navigational styling

how yours looks:
![screen shot 2016-03-18 at 3 29 10 pm](https://cloud.githubusercontent.com/assets/7436666/13893791/886e8d06-ed1e-11e5-9d05-0725e8f88e19.png)

how it should be:
![screen shot 2016-03-18 at 3 26 24 pm](https://cloud.githubusercontent.com/assets/7436666/13893708/11b6b92c-ed1e-11e5-8521-2c2f49e559e6.png)

option:
links should be yellow when active, no yellow background (except for "sign up" button)

**Comment by geekwise-alonzo-yrigollen** [comment]
navigational styling complete;

see ya next week, take care
